<!--*******************************************************-->
<!-- BODY -->
<!--*******************************************************-->
        
          <!--*************************-->
          <!-- Table 1 - ovens main screen -->
          <table border="1">
          
            <!-- Table 1, Row1 - ovens main screen -->
            <tr>
              <!--*************************-->
              <td>
                <a href="Oven_Main?ovenIndex=1">
                  <h2>
                    <strong>Pec 1</strong>
                  </h2>               
                  <img src="pictures/Oven.png" alt="Oven" height="142">   
                </a>
              </td>    
             <!--*************************-->
              <td>
                <a href="Oven_Main?ovenIndex=2">
                  <h2>
                    <strong>Pec 2</strong>
                  </h2>               
                  <img src="pictures/Oven.png" alt="Oven" height="142">   
                </a>
              </td>    
              
             <!--*************************-->
              <td>
                <a href="Oven_Main?ovenIndex=3">
                  <h2>
                    <strong>Pec 3</strong>
                  </h2>               
                  <img src="pictures/Oven.png" alt="Oven" height="142">   
                </a>
              </td>     
            </tr>    
            
            
              
            <!--*************************-->
            <!-- Table 1, Row2 - ovens main screen -->  
            <tr>
            
              <!--*************************-->
              <td align="center">
                <span class="valWindow"><?= $oven1Main1 ?></span>
              </td>
            
              <!--*************************-->
              <td align="center">
                <span class="valWindow"><?= $oven2Main1 ?></span>
              </td>
              
              <!--*************************-->
              <td align="center">
                <span class="valWindow"><?= $oven3Main1 ?></span>
              </td>
            </tr>
              
              
              
            <!--*************************-->
            <!-- Table 1, Row3 - ovens main screen -->  
            <tr>
            
              <!--*************************-->
              <td align="center">
                <span class="valWindow"><?= $oven1Main2 ?></span>
              </td>
              
              <!--*************************-->
              <td align="center">
                <span class="valWindow"><?= $oven2Main2 ?></span>
              </td>
              
              <!--*************************-->
              <td align="center">
                <span class="valWindow"><?= $oven3Main2 ?></span>
              </td>
            </tr>    
          </table>
 
      
 