<!--*******************************************************-->
<!-- BODY -->
<!--*******************************************************-->
        
          <!--*************************-->
          <!-- Table 1 - ovens main screen -->
          <table border="1">
          
            <!-- Table 1, Row1 - ovens main screen -->
            <tr>
            
              <!--*************************-->
              <td>
                <h2>
                  <strong>Pec 1</strong>
                </h2>
                <a href="Index.php?stranka=Main">
                  <img src="pictures/Oven.png" alt="Oven" height="142">   
                </a>
              </td>    
              
             <!--*************************-->
              <td>
                <h2>
                  <strong>Pec 2</strong>
                </h2>
                <a href="Index.php?stranka=Main">
                  <img src="pictures/Oven.png" alt="Oven" height="142">   
                </a>
              </td>    
              
             <!--*************************-->
              <td>
                <h2>
                  <strong>Pec 2</strong>
                </h2>
                <a href="Index.php?stranka=Main">
                  <img src="pictures/Oven.png" alt="Oven" height="142">   
                </a>
              </td>     
            </tr>    
            
            
              
            <!--*************************-->
            <!-- Table 1, Row2 - ovens main screen -->  
            <tr>
            
              <!--*************************-->
              <td>
                <strong>Teplota:  </strong>
              </td>
            
              <!--*************************-->
              <td>
                <strong>Teplota: </strong>
              </td>
              
              <!--*************************-->
              <td>
                <strong>Teplota:  </strong>
              </td>
            </tr>
              
              
              
            <!--*************************-->
            <!-- Table 1, Row3 - ovens main screen -->  
            <tr>
            
              <!--*************************-->
              <td>
                <strong>Teplota: </strong>
              </td>
              
              <!--*************************-->
              <td>
                <strong>Teplota: </strong>
              </td>
              
              <!--*************************-->
              <td>
                <strong>Teplota: </strong>
              </td>
            </tr>    
          </table>
 
      
 