<!--*******************************************************-->
<!-- BODY -->
<!--*******************************************************-->
        
          <!--*************************-->
          <!-- Table 1 - ovens main screen -->
          <table class="valueTable">       
            <!-- Table 1, Row1 -->
            <tr>    
              <td> <strong>Status:</strong> </td> 
              <td></td>
              <td> <span class="valWindow"><?= $ovenState ?></span> </td>         
            </tr>    
            
            <tr>    
              <td> <strong>Aktuální teplota:</strong> </td> 
              <td></td>
              <td> <span class="valWindow"><?= $actTemp ?></span> </td>      
            </tr>    
            
            <tr>    
              <td> <strong>Žádaná teplota:</strong> </td> 
              <td></td>
              <td> <span class="valWindow"><?= $reqTemp ?></span> </td>      
            </tr>    

            <tr>    
              <td> <strong>Cílová teplota kroku:</strong> </td> 
              <td></td>
              <td> <span class="valWindow"><?= $stepTemp ?></span> </td>      
            </tr> 
            
            <tr>    
              <td> <strong>Aktuální výkon:</strong> </td> 
              <td></td>
              <td> <span class="valWindow"><?= $actPower ?></span> </td>      
            </tr> 
            
            <tr>    
              <td> <strong>Aktuální délka programu:</strong> </td> 
              <td> <span class="valWindow"><?= $actDurH ?></span> </td>  
              <td> <span class="valWindow"><?= $actDurM ?></span> </td>      
            </tr>    
            
            <tr>    
              <td> <strong>Práce výkonového členu:</strong> </td> 
              <td></td>
              <td> <span class="valWindow"><?= $actPowerTime ?></span> </td>      
            </tr>  
          </table>
 
      
 