<!--*******************************************************-->
<!-- BODY -->
<!--*******************************************************-->
        
          <!--*************************-->
          <!-- Table 1 - ovens main screen -->
          <table border="1">
          
            <!-- Table 1, Row1 -->
            <tr>    
              <td>
                <h2>
                  <strong>Pec 1</strong>
                </h2>              
              </td>          
            </tr>    
            
            
              
            <!--*************************-->
            <!-- Table 1, Row2 - ovens main screen -->  
            <tr>
            
              <!--*************************-->
              <td>
                <strong>Teplota: </strong>
              </td>
            
              <!--*************************-->
              <td>
                <strong>Teplota: </strong>
              </td>
              
              <!--*************************-->
              <td>
                <strong>Teplota:  </strong>
              </td>
            </tr>
              
              
              
            <!--*************************-->
            <!-- Table 1, Row3 - ovens main screen -->  
            <tr>
            
              <!--*************************-->
              <td>
                <strong>Teplota: </strong>
              </td>
              
              <!--*************************-->
              <td>
                <strong>Teplota: </strong>
              </td>
              
              <!--*************************-->
              <td>
                <strong>Teplota: </strong>
              </td>
            </tr>    
          </table>
 
      
 