<!--*******************************************************-->
<!-- BODY -->
<!--*******************************************************-->
        
          <!--*************************-->
          <!-- Table 1 - ovens main screen -->
          <table class="valueTable">       
            <!-- Table 1, Row1 -->
            <tr>    
              <td> <strong>Číslo programu:</strong> </td> 
              <td> <span class="valWindow"><?= $prgIndex ?></span> </td>         
            </tr>    
            
            <tr>    
              <td> <strong>Název programu:</strong> </td> 
              <td> <span class="valWindow"><?= $prgName ?></span> </td>      
            </tr>    
            
            <tr>    
              <td> <strong>Krok programu:</strong> </td> 
              <td> <span class="valWindow"><?= $prgStep ?></span> </td>      
            </tr>    

            <tr>    
              <td> <strong>teplota kroku:</strong> </td> 
              <td> <span class="valWindow"><?= $prgTemp ?></span> </td>      
            </tr> 
            
            <tr>    
              <td> <strong>Zbývající čas(h):</strong> </td> 
              <td> <span class="valWindow"><?= $prgTimeH ?></span> </td>      
            </tr> 
            
            <tr>    
              <td> <strong>Zbávající čas(m):</strong> </td>             
              <td> <span class="valWindow"><?= $prgTimeM ?></span> </td>     
            </tr>    
            
          </table>
 
      
 